version: "3"

services:
  bot:
    build: ./
    container_name: bot
    volumes:
      - ./:/usr/src/app
    environment:
      - NODE_ENV=production
    expose:
      - "8080"
    command: "npm start"